services:
  atm_api.web:
    image: ${DOCKER_REGISTRY-}atmapiweb
    build:
      context: .
      dockerfile: src/ATM_API.Web/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=atm.database;Port=5432;Database=ATM_DB;Username=postgres;Password=postgres
    depends_on:
      - atm.database

  atm.database:
    image: postgres:15
    container_name:  atm.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ATM_DB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
