version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ATM_API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=atm_db;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: