version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    ports:
      - "8080:80"
      - "5678:5678"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=atm_db;Username=postgres;Password=postgres
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ATM_DB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
